// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A love letter generator with phrase repetition reasoning.
 *
 * - generateLoveLetter - A function that generates a love letter with consideration for phrase repetition.
 * - LoveLetterInput - The input type for the generateLoveLetter function.
 * - LoveLetterOutput - The return type for the generateLoveLetter function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const LoveLetterInputSchema = z.object({
  recipientName: z.string().describe('The name of the recipient of the love letter.'),
  specificPhrases: z.string().describe('Specific phrases to consider for repetition in the letter.'),
  userDetails: z.string().describe('The description of the person writing the love letter'),
  tone: z.string().describe('The tone of the love letter (e.g., romantic, sweet, passionate).'),
});
export type LoveLetterInput = z.infer<typeof LoveLetterInputSchema>;

const LoveLetterOutputSchema = z.object({
  letter: z.string().describe('The generated love letter.'),
});
export type LoveLetterOutput = z.infer<typeof LoveLetterOutputSchema>;

export async function generateLoveLetter(input: LoveLetterInput): Promise<LoveLetterOutput> {
  return loveLetterFlow(input);
}

const prompt = ai.definePrompt({
  name: 'loveLetterPrompt',
  input: {schema: LoveLetterInputSchema},
  output: {schema: LoveLetterOutputSchema},
  prompt: `You are an expert love letter writer. You will generate a love letter for {{recipientName}} considering the user's request about repeating phrases to make the letter more heartfelt and beautiful.

User Details: {{userDetails}}
Recipient Name: {{recipientName}}
Tone: {{tone}}
Specific Phrases to Consider: {{specificPhrases}}

Instructions: Reason whether repeating the provided phrases would enhance the letter's emotional impact, making it sound more heartfelt and beautiful. Use your reasoning to determine if the phrase would be appropriate to use, and if so, repeat the phrase.

Love Letter:
`,
});

const loveLetterFlow = ai.defineFlow(
  {
    name: 'loveLetterFlow',
    inputSchema: LoveLetterInputSchema,
    outputSchema: LoveLetterOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
